=== AnaMijailovic/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xsd/scientific_paper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/AnaMijailovic/XML-Tim19"
    xmlns="https://github.com/AnaMijailovic/XML-Tim19">
    <xs:complexType name="TPerson">
        <xs:sequence>
            <xs:element name="first_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="middle_name" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="simple_paragraph_elements">
        <xs:sequence>
            <xs:element minOccurs="0" name="b" type="TEmphasis"/>
            <xs:element minOccurs="0" name="i" type="TEmphasis"/>
            <xs:element minOccurs="0" name="u" type="TEmphasis"/>
            <xs:element minOccurs="0" ref="unordered_list"/>
            <xs:element minOccurs="0" ref="ordered_list"/>
            <xs:element minOccurs="0" ref="quote"/>
        </xs:sequence>
    </xs:group>
    <xs:complexType mixed="true" name="TSimpleParagraph">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:group ref="simple_paragraph_elements"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="TComplexParagraph" mixed="true">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="image"/>
                <xs:element ref="table"/>
                <xs:group ref="simple_paragraph_elements"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TEmphasis">
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element minOccurs="0" name="b" type="TEmphasis"/>
            <xs:element minOccurs="0" name="i" type="TEmphasis"/>
            <xs:element minOccurs="0" name="u" type="TEmphasis"/>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="TItem">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:element name="scientific_paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" ref="author"/>
                            <xs:element name="keyword" maxOccurs="15">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="25"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="abstract">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="paragraph"
                                            type="TSimpleParagraph"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" ref="chapter"/>
                            <xs:element name="references">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="reference"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="recieved_date" type="xs:date"/>
            <xs:attribute name="revised_date" type="xs:date"/>
            <xs:attribute name="accepted_date" type="xs:date"/>
            <xs:attribute name="status" default="PENDING" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="REVIEWING"/>
                        <xs:enumeration value="ACCEPTED"/>
                        <xs:enumeration value="REJECTED"/>
                        <xs:enumeration value="REVISION"/>
                        <xs:enumeration value="PENDING"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute default="1" name="version" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="author">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TPerson">
                    <xs:sequence>
                        <xs:element minOccurs="0" name="email">
                            <xs:simpleType>
                                <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="affiliation">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="name" type="xs:string"/>
                                    <xs:element name="city" type="xs:string"/>
                                    <xs:element name="state" type="xs:string" minOccurs="0"/>
                                    <xs:element name="country" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="heading"/>
                <xs:element maxOccurs="unbounded" name="paragraph" type="TComplexParagraph"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="chapter"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="level" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="src" type="xs:string" use="required"/>
            <xs:attribute name="width" type="xs:positiveInteger"/>
            <xs:attribute name="height" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="unordered_list">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="item" type="TItem"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="style" default="circle">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="disc"/>
                        <xs:enumeration value="circle"/>
                        <xs:enumeration value="square"/>
                        <xs:enumeration value="none"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="ordered_list">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="item" type="TItem"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="type" default="1">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="1"/>
                        <xs:enumeration value="A"/>
                        <xs:enumeration value="a"/>
                        <xs:enumeration value="I"/>
                        <xs:enumeration value="i"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="tr" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="th" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="td" type="xs:string" maxOccurs="unbounded"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="quote">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="source" type="xs:string"/>
                <xs:element name="text" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="heading" type="xs:string"/>
    <xs:element name="reference">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element maxOccurs="unbounded" name="reference_author" type="TPerson"> </xs:element>
                <xs:element name="publisher" type="xs:string"/>
                <xs:element name="year_of_publication" type="xs:gYear"/>
                <xs:element name="pages" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnaMijailovic/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xml/scientificPaperGenerated2.xml
<?xml version="1.0" encoding="UTF-8"?>
<xm:scientific_paper xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
 xmlns:xm="https://github.com/AnaMijailovic/XML-Tim19"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/AnaMijailovic/XML-Tim19 file:/C:/Users/anaam/Desktop/XML%20Project/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xsd/scientific_paper.xsd" id="ID000">
    <xm:head>
        <xm:title lang="lang0">title0</xm:title>
        <xm:title lang="lang1">title1</xm:title>
        <xm:author>
            <xm:first_name>first_name0</xm:first_name>
            <xm:last_name>last_name0</xm:last_name>
            <xm:affiliation>
                <xm:name>name0</xm:name>
                <xm:city>city0</xm:city>
                <xm:country>country0</xm:country>
            </xm:affiliation>
        </xm:author>
        <xm:author>
            <xm:first_name>first_name1</xm:first_name>
            <xm:last_name>last_name1</xm:last_name>
            <xm:affiliation>
                <xm:name>name1</xm:name>
                <xm:city>city1</xm:city>
                <xm:country>country1</xm:country>
            </xm:affiliation>
        </xm:author>
        <xm:keyword>keyword0</xm:keyword>
        <xm:keyword>keyword1</xm:keyword>
    </xm:head>
    <xm:body>
        <xm:abstract id="ID001">
            <xm:paragraph id="ID002">
            </xm:paragraph>
            <xm:paragraph id="ID003">
            </xm:paragraph>
        </xm:abstract>
        <xm:chapter id="ID004" level="3">
            <xm:heading>heading0</xm:heading>
            <xm:paragraph id="ID005">
                <xm:table id="ID006">
                    <xm:name>name2</xm:name>
                    <xm:description>description0</xm:description>
                    <xm:tr>
                        <xm:td>td0</xm:td>
                        <xm:td>td1</xm:td>
                    </xm:tr>
                    <xm:tr>
                        <xm:th>th0</xm:th>
                        <xm:th>th1</xm:th>
                    </xm:tr>
                </xm:table>
                <xm:image id="ID007" src="src0">
                    <xm:name>name3</xm:name>
                    <xm:description>description1</xm:description>
                </xm:image>
            </xm:paragraph>
            <xm:paragraph id="ID008">
            </xm:paragraph>
        </xm:chapter>
        <xm:chapter id="ID009" level="3">
            <xm:heading>heading1</xm:heading>
            <xm:paragraph id="ID010">
                <xm:image id="ID011" src="src1">
                    <xm:name>name4</xm:name>
                    <xm:description>description2</xm:description>
                </xm:image>
                <xm:image id="ID012" src="src2">
                    <xm:name>name5</xm:name>
                    <xm:description>description3</xm:description>
                </xm:image>
            </xm:paragraph>
            <xm:paragraph id="ID013">
                <xm:table id="ID014">
                    <xm:name>name6</xm:name>
                    <xm:description>description4</xm:description>
                    <xm:tr>
                        <xm:th>th2</xm:th>
                        <xm:th>th3</xm:th>
                    </xm:tr>
                    <xm:tr>
                        <xm:td>td2</xm:td>
                        <xm:td>td3</xm:td>
                    </xm:tr>
                </xm:table>
                <xm:table id="ID015">
                    <xm:name>name7</xm:name>
                    <xm:description>description5</xm:description>
                    <xm:tr>
                        <xm:th>th4</xm:th>
                        <xm:th>th5</xm:th>
                    </xm:tr>
                    <xm:tr>
                        <xm:th>th6</xm:th>
                        <xm:th>th7</xm:th>
                    </xm:tr>
                </xm:table>
            </xm:paragraph>
        </xm:chapter>
        <xm:references id="ID016">
            <xm:reference id="ID017">
                <xm:title>title2</xm:title>
                <xm:reference_author>
                    <xm:first_name>first_name2</xm:first_name>
                    <xm:last_name>last_name2</xm:last_name>
                </xm:reference_author>
                <xm:reference_author>
                    <xm:first_name>first_name3</xm:first_name>
                    <xm:last_name>last_name3</xm:last_name>
                </xm:reference_author>
                <xm:publisher>publisher0</xm:publisher>
                <xm:year_of_publication>2006</xm:year_of_publication>
                <xm:pages>pages0</xm:pages>
            </xm:reference>
            <xm:reference id="ID018">
                <xm:title>title3</xm:title>
                <xm:reference_author>
                    <xm:first_name>first_name4</xm:first_name>
                    <xm:last_name>last_name4</xm:last_name>
                </xm:reference_author>
                <xm:reference_author>
                    <xm:first_name>first_name5</xm:first_name>
                    <xm:last_name>last_name5</xm:last_name>
                </xm:reference_author>
                <xm:publisher>publisher1</xm:publisher>
                <xm:year_of_publication>2006</xm:year_of_publication>
                <xm:pages>pages1</xm:pages>
            </xm:reference>
        </xm:references>
    </xm:body>
</xm:scientific_paper>
