=== AnaMijailovic/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xsd/scorecard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/AnaMijailovic/XML-Tim19/scorecard"
    xmlns="https://github.com/AnaMijailovic/XML-Tim19/scorecard"> 
    <xs:element name="scorecard">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="originality">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="importance">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="clarity">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relevance">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="value">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="purpose">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="courtesy">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="impact_factor">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="first_impressions">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="layout_and_format">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="design">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="methodology">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="scientific_approach">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="language">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>        
                <xs:element name="results">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="findings">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="research_implications">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="practical_implications">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="social_implications">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>     
                <xs:element name="research_limitations">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="further_discussion">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>           
                <xs:element name="justified_conclusions">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="acknowledgements">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="figures">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tables">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="references">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="supplementary_data">
                    <xs:complexType>
                        <xs:attribute name="score" type="score"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="score">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AnaMijailovic/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xml/scorecardInstance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<scorecard xmlns="https://github.com/AnaMijailovic/XML-Tim19/scorecard"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/AnaMijailovic/XML-Tim19/scorecard file:/C:/Users/Dule/Desktop/WEB-MATERIJALI/XML-PROJEKAT/XML-Tim19/scientific_papers/scientific_papers/src/main/resources/xsd/scorecard.xsd">
    <originality score="1"/>
    <importance score="2"/>
    <clarity score="3"/>
    <relevance score="4"/>
    <value score="5"/>
    <purpose score="1"/>
    <courtesy score="2"/>
    <impact_factor score="3"/>
    <first_impressions score="4"/>
    <layout_and_format score="5"/>
    <design score="1"/>
    <methodology score="2"/>
    <scientific_approach score="3"/>
    <language score="4"/>
    <results score="5"/>
    <findings score="1"/>
    <research_implications score="2"/>
    <practical_implications score="3"/>
    <social_implications score="4"/>
    <research_limitations score="5"/>
    <further_discussion score="1"/>
    <justified_conclusions score="2"/>
    <acknowledgements score="3"/>
    <figures score="4"/>
    <tables score="5"/>
    <references score="1"/>
    <supplementary_data score="2"/>
</scorecard>
